use serde::{Deserialize, Serialize};

/// Hardware profile describing available GPU/CPU resources.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HardwareProfile {
    pub vram_gb: f64,
    pub ram_gb: Option<f64>,
}

/// Result of model selection routing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelSelection {
    pub model: String,
    pub mode: String,
    pub reason: String,
}

/// Entry in the local model catalog.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelEntry {
    pub model: String,
    pub required_vram_gb: f64,
    pub ram_gb: f64,
    pub tags: Vec<String>,
    pub reason: String,
}

/// Benchmark result for a model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BenchmarkResult {
    pub model: String,
    pub tokens_per_second: f64,
    pub latency_ms: f64,
    pub vram_gb: f64,
    pub cache_hit: bool,
    pub ts: String,
}

/// Plugin manifest loaded from a plugin directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginManifest {
    pub name: String,
    pub trust_level: String,
    pub path: String,
    pub description: Option<String>,
}

// ── Privacy ─────────────────────────────────────────────────────────────────

/// Single privacy item in a report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrivacyItem {
    pub what: String,
    pub destination: String,
    pub risk: String,
}

/// Full privacy analysis report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PrivacyReport {
    pub level: String,
    pub items: Vec<PrivacyItem>,
}

/// Agent permissions for sandbox execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPermissions {
    #[serde(default)]
    pub allowed_folders: Vec<String>,
    #[serde(default)]
    pub network: bool,
    #[serde(default)]
    pub shell: bool,
}

/// Agent plan generated by the task simulator.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPlan {
    pub steps: Vec<String>,
    pub required_permissions: Vec<String>,
    pub estimated_tokens: u64,
}

/// A contradiction match between two claims.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContradictionMatch {
    pub left: String,
    pub right: String,
    pub similarity: f64,
    pub sentiment_left: String,
    pub sentiment_right: String,
}

// ── Benchmark ────────────────────────────────────────────────────────────────

/// Single benchmark run result for a model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BenchmarkRunResult {
    pub model: String,
    pub runs: usize,
    pub avg_tokens_per_second: f64,
    pub avg_time_to_first_token_ms: f64,
    pub avg_total_time_ms: f64,
    pub min_tps: f64,
    pub max_tps: f64,
    pub stddev_tps: f64,
    pub vram_estimate_gb: f64,
    pub privacy_level: String,
    pub error: Option<String>,
    pub cached_at: Option<f64>,
}
